#!/bin/bash
### BEGIN INIT INFO
# Provides:          Load nav.HAT driver
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Loads the nav.HAT driver during booting.
# Description:       
### END INIT INFO

# You need to copy load_driver_navHAT.sh to /etc/init.d before adding the service
# Add service: sudo update-rc.d -f load_driver_navHAT defaults
# Remove service: sudo update-rc.d -f load_driver_navHAT remove
#
# Error and info messages will be written to the kernel ring buffer.
# sys> dmesg


# You might need to change the path to the driver
driverPath=/home/pi/naviDev.ko


ttyDev=/dev/naviDev.tty

start() {
    echo "Loading $driverPath" > /dev/kmsg
    insmod $driverPath
    if [ $? -ne 0 ]
    then
        echo "ERROR: Could not load $driverPath." > /dev/kmsg
        exit 1
    fi
    chown pi:pi $ttyDev
    if [ $? -ne 0 ]
    then
        echo "ERROR: Could not set owner for $ttyDev. You might need super user rights to access the device." > /dev/kmsg
        exit 1
    fi
}
stop() {
    echo "Unloading $driverPath" > /dev/kmsg
    rmmod $driverPath
    if [ $? -ne 0 ]
    then
        echo "ERROR: Unloading kernel module failed." > /dev/kmsg
        exit 1
    fi   
}

case "$1" in
  start)
        start;;
  stop)
        stop;;
   restart)
        stop
        start;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1;;
esac
exit $?

